base_url = "https://va3zza.com"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

[markdown]
highlight_code = true

[extra]
name = "Evan Pratten"
profession = "Software Developer"
email = "mail@va3zza.com"
twitter = "ewpratten"
github = "ewpratten"
qrz = "va3zza"