base_url = "https://va3zza.com"
title = "Evan Pratten"
description = "Evan Pratten is a college student, amateur radio operator, software developer, and more. This is his website."
default_language = "en"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
minify_html = false

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true

[extra]
# Site meta
site_domain = "va3zza.com"

# Me
author = "Evan Pratten"
profile_photo = "https://avatars.githubusercontent.com/u/21065412"
email = "mail@va3zza.com"

# Social media
social_twitter = "ewpratten"
social_github = "ewpratten"
social_qrz = "va3zza"
social_linkedin = "ewpratten"